<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.0 room.glb -t -s
-->

<script lang="ts">
  import * as THREE from 'three'

  import type { Snippet } from 'svelte'
  import { T, type Props } from '@threlte/core'
  import { useGltf } from '@threlte/extras'

  let {
    fallback,
    error,
    children,
    ref = $bindable(),
    ...props
  }: Props<THREE.Group> & {
    ref?: THREE.Group
    children?: Snippet<[{ ref: THREE.Group }]>
    fallback?: Snippet
    error?: Snippet<[{ error: Error }]>
  } = $props()

  type GLTFResult = {
    nodes: {
      Cube: THREE.Mesh
      couch001: THREE.Mesh
      armchair001: THREE.Mesh
      chair_C001: THREE.Mesh
      cabinet_medium_decorated001: THREE.Mesh
      table_small001: THREE.Mesh
      lamp_desk001: THREE.Mesh
      rug_rectangle_stripes_A001: THREE.Mesh
      shelf_B_small_decorated001: THREE.Mesh
      pictureframe_large_A001: THREE.Mesh
      pictureframe_medium001: THREE.Mesh
      pictureframe_large_B001: THREE.Mesh
      lamp_standing001: THREE.Mesh
    }
    materials: {
      furniture_texture: THREE.MeshStandardMaterial
    }
  }

  const gltf = useGltf<GLTFResult>('/tiny-creature/room.glb')
</script>

<T.Group
  bind:ref
  dispose={false}
  {...props}
>
  {#await gltf}
    {@render fallback?.()}
  {:then gltf}
    <T.Mesh
      castShadow
      receiveShadow
      geometry={gltf.nodes.Cube.geometry}
      position={[0, 2, 0]}
      scale={[1, 0.5, 1]}
    >
      <T.MeshStandardMaterial side={THREE.DoubleSide} envMapIntensity={0.1} />
  </T.Mesh>
    <T.Mesh
      castShadow
      receiveShadow
      geometry={gltf.nodes.couch001.geometry}
      material={gltf.materials.furniture_texture}
      position={[3.08, 0, -0.64]}
      rotation={[0, -1.53, 0]}
    />
    <T.Mesh
      castShadow
      receiveShadow
      geometry={gltf.nodes.armchair001.geometry}
      material={gltf.materials.furniture_texture}
      position={[1.4, 0, -3.1]}
      rotation={[0, -0.23, 0]}
    />
    <T.Mesh
      castShadow
      receiveShadow
      geometry={gltf.nodes.chair_C001.geometry}
      material={gltf.materials.furniture_texture}
      position={[-3.11, 0, -3.01]}
      rotation={[0, 0.47, 0]}
    />
    <T.Mesh
      castShadow
      receiveShadow
      geometry={gltf.nodes.cabinet_medium_decorated001.geometry}
      material={gltf.materials.furniture_texture}
      position={[-1.02, 0, -3.56]}
    />
    <T.Mesh
      castShadow
      receiveShadow
      geometry={gltf.nodes.table_small001.geometry}
      material={gltf.materials.furniture_texture}
      position={[3.2, 0, 1.64]}
    />
    <T.Mesh
      castShadow
      receiveShadow
      geometry={gltf.nodes.lamp_desk001.geometry}
      material={gltf.materials.furniture_texture}
      position={[3.13, 0.97, 1.67]}
      rotation={[Math.PI, -1.17, Math.PI]}
    />
    <T.Mesh
      castShadow
      receiveShadow
      geometry={gltf.nodes.rug_rectangle_stripes_A001.geometry}
      material={gltf.materials.furniture_texture}
      position={[-0.64, 0, 1.37]}
      rotation={[0, -0.64, 0]}
    />
    <T.Mesh
      castShadow
      receiveShadow
      geometry={gltf.nodes.shelf_B_small_decorated001.geometry}
      material={gltf.materials.furniture_texture}
      position={[4, 2.25, 2.73]}
      rotation={[0, -Math.PI / 2, 0]}
    />
    <T.Mesh
      castShadow
      receiveShadow
      geometry={gltf.nodes.pictureframe_large_A001.geometry}
      material={gltf.materials.furniture_texture}
      position={[-2.61, 2.38, -4.02]}
    />
    <T.Mesh
      castShadow
      receiveShadow
      geometry={gltf.nodes.pictureframe_medium001.geometry}
      material={gltf.materials.furniture_texture}
      position={[-1.28, 2.57, -4.03]}
    />
    <T.Mesh
      castShadow
      receiveShadow
      geometry={gltf.nodes.pictureframe_large_B001.geometry}
      material={gltf.materials.furniture_texture}
      position={[4, 2.77, -0.17]}
      rotation={[0, -Math.PI / 2, 0]}
    />
    <T.Mesh
      castShadow
      receiveShadow
      geometry={gltf.nodes.lamp_standing001.geometry}
      material={gltf.materials.furniture_texture}
      position={[3.22, 0, -3.24]}
    />
  {:catch err}
    {@render error?.({ error: err })}
  {/await}

  {@render children?.({ ref })}
</T.Group>
